// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/tilau2328/entcontrib/entproto/internal/entprototest/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messagewithenumFields := schema.MessageWithEnum{}.Fields()
	_ = messagewithenumFields
}
