// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package todofed

import (
	"github.com/tilau2328/entcontrib/entgql/internal/todofed/ent/todo"
)

type TodoInput struct {
	Status     todo.Status `json:"status"`
	Priority   *int        `json:"priority"`
	Text       string      `json:"text"`
	Parent     *int        `json:"parent"`
	CategoryID *int        `json:"category_id"`
}
